name: Deploy to firebase host
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Prepare and deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN}}
        run: |
          npm install
          npx ng deploy --token $FIREBASE_TOKEN
